//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Vava
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Кто.
    /// </summary>
    // *** Start programmer edit section *** (Кто CustomAttributes)

    // *** End programmer edit section *** (Кто CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("КтоE", new string[] {
            "Код as \'Код\'",
            "Дата as \'Дата\'",
            "Сотрудники as \'Сотрудники\'",
            "Сотрудники.Фамилия as \'Фамилия\'"}, Hidden=new string[] {
            "Сотрудники.Фамилия"})]
    [MasterViewDefineAttribute("КтоE", "Сотрудники", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Фамилия")]
    [View("КтоL", new string[] {
            "Код as \'Код\'",
            "Дата as \'Дата\'",
            "Сотрудники.Фамилия as \'Фамилия\'",
            "Сотрудники.Имя as \'Имя\'",
            "Сотрудники.Отчество as \'Отчество\'"})]
    public class Кто : ICSSoft.STORMNET.DataObject
    {
        
        private int fКод;
        
        private System.DateTime fДата;
        
        private IIS.Vava.Сотрудники fСотрудники;
        
        // *** Start programmer edit section *** (Кто CustomMembers)

        // *** End programmer edit section *** (Кто CustomMembers)

        
        /// <summary>
        /// Дата.
        /// </summary>
        // *** Start programmer edit section *** (Кто.Дата CustomAttributes)

        // *** End programmer edit section *** (Кто.Дата CustomAttributes)
        public virtual System.DateTime Дата
        {
            get
            {
                // *** Start programmer edit section *** (Кто.Дата Get start)

                // *** End programmer edit section *** (Кто.Дата Get start)
                System.DateTime result = this.fДата;
                // *** Start programmer edit section *** (Кто.Дата Get end)

                // *** End programmer edit section *** (Кто.Дата Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Кто.Дата Set start)

                // *** End programmer edit section *** (Кто.Дата Set start)
                this.fДата = value;
                // *** Start programmer edit section *** (Кто.Дата Set end)

                // *** End programmer edit section *** (Кто.Дата Set end)
            }
        }
        
        /// <summary>
        /// Код.
        /// </summary>
        // *** Start programmer edit section *** (Кто.Код CustomAttributes)

        // *** End programmer edit section *** (Кто.Код CustomAttributes)
        public virtual int Код
        {
            get
            {
                // *** Start programmer edit section *** (Кто.Код Get start)

                // *** End programmer edit section *** (Кто.Код Get start)
                int result = this.fКод;
                // *** Start programmer edit section *** (Кто.Код Get end)

                // *** End programmer edit section *** (Кто.Код Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Кто.Код Set start)

                // *** End programmer edit section *** (Кто.Код Set start)
                this.fКод = value;
                // *** Start programmer edit section *** (Кто.Код Set end)

                // *** End programmer edit section *** (Кто.Код Set end)
            }
        }
        
        /// <summary>
        /// Кто.
        /// </summary>
        // *** Start programmer edit section *** (Кто.Сотрудники CustomAttributes)

        // *** End programmer edit section *** (Кто.Сотрудники CustomAttributes)
        [PropertyStorage(new string[] {
                "Сотрудники"})]
        [NotNull()]
        public virtual IIS.Vava.Сотрудники Сотрудники
        {
            get
            {
                // *** Start programmer edit section *** (Кто.Сотрудники Get start)

                // *** End programmer edit section *** (Кто.Сотрудники Get start)
                IIS.Vava.Сотрудники result = this.fСотрудники;
                // *** Start programmer edit section *** (Кто.Сотрудники Get end)

                // *** End programmer edit section *** (Кто.Сотрудники Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Кто.Сотрудники Set start)

                // *** End programmer edit section *** (Кто.Сотрудники Set start)
                this.fСотрудники = value;
                // *** Start programmer edit section *** (Кто.Сотрудники Set end)

                // *** End programmer edit section *** (Кто.Сотрудники Set end)
            }
        }
        
        // *** Start programmer edit section *** (Кто.Отправить CustomAttributes)

        // *** End programmer edit section *** (Кто.Отправить CustomAttributes)
        [ICSSoft.STORMNET.AccessType(ICSSoft.STORMNET.AccessType.none)]
        public virtual void Отправить()
        {
            // *** Start programmer edit section *** (Кто.Отправить method implementation)

            return;
            // *** End programmer edit section *** (Кто.Отправить method implementation)
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "КтоE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View КтоE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("КтоE", typeof(IIS.Vava.Кто));
                }
            }
            
            /// <summary>
            /// "КтоL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View КтоL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("КтоL", typeof(IIS.Vava.Кто));
                }
            }
        }
    }
}
